version: '3.8'

services:
  php:
    image: php:8.2-fpm-alpine
    container_name: php_whatsmyip
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx_whatsmyip
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
